redis:
  host: localhost
  password:
  port: 6379
  dbIndex: 0
  maxIdle: 50
  minIdle: 50
  maxTotal: 50
  timeout: 5
  maxWait: 10
  shutdown: 100
server:
  port: 81
  error:
    include-message: always
  servlet:
    context-path: "/api/audit-service"
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: ms-audit service
  datasource:
    name: datasource
    url: jdbc:postgresql://localhost:5432/msaudit
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    platform: postgres
    filters: stat
    maxActive: 80
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 80
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size : 80
      minimum-idle: 10
      pool-name : MsAuditConnPool
  jpa:
    hibernate:
      ddl-auto: update
      connection:
        provider_class : "com.zaxxer.hikari.hibernate.HikariConnectionProvider"
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true
        order_updates: true
        batch_versioned_data: true
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
config:
  housekeep:
    interval:
      audit: 7 days
  scheduler:
    audit:
      doHousekeepAudit: "0 0 4 * * ?" #everyday 4:00:00 a.m.
  internal:
    api:
      micro:
        path: '/api/audit-service'
      key: 4da85148-6e25-4a2e-9744-382adf1c3e9c
swagger:
  #host: "localhost:${server.port}" #test from local
  host: "localhost:80" #test using gateway
